### ISSUE TITLE
example for extracting mesh or point cloud

### ISSUE THREAD

**Issue by yotofu** [TQTQliu/GeFu#1]
Really a great job! Any plan to give a example for extracting mesh or point cloud?

**Comment by TQTQliu** [comment]
Thanks for your attention, I just add the code to recontruct point clouds.  Add the ```save_ply True``` parameter to save the reconstruted point clouds. Take the DTU as an example, just run:
```
python run.py --type evaluate --cfg_file configs/gefu/dtu_pretrain.yaml gefu.eval_depth True save_ply True
```
Since the model can produce depth maps, the pixels in the image can be unprojected into 3D space to obtain point clouds. 
However, it is worth noting that in the code just provided, we did not perform the depth filtering operation,  so the resulting point cloud will be large in number and contain some noise. If a more accurate point cloud is needed, masks can be generated by checking the geometric consistency of depth maps. Refer to the fusion method [pcd](https://github.com/TQTQliu/ET-MVSNet/blob/main/test_dtu_pcd.py) or [dypcd](https://github.com/TQTQliu/ET-MVSNet/blob/main/test_dtu_dypcd.py).

**Comment by yotofu** [comment]
Thanks! I found config below
![image](https://github.com/TQTQliu/GeFu/assets/24996527/6b1288e7-87a9-424d-989a-345967b0b9c5)
is there any method to extract mesh for gefu?

**Comment by TQTQliu** [comment]
This is the configuration code inherited from other repo. We didn't use it. Because in our method, the novel view synthesis does not require mesh extraction. However, since the model can produce the depth map and point clouds, it can also be converted into corresponding mesh if you want.

**Comment by TQTQliu** [comment]
Hi, we provide a case on point cloud to mesh conversion [here](https://github.com/TQTQliu/GeFu/blob/e582c3ac99ed4b92841a39be3b17e4b23d5b7c36/run.py#L132), hoping it will be helpful to you. 
However, it's worth noting that our method does not focus on surface reconstruction but rather on the quality of novel view synthesis. In contrast, methods like [NeuS](https://lingjie0206.github.io/papers/NeuS/) focus on surface reconstruction and can produce good mesh.

**Comment by yotofu** [comment]
Got it, thanks a lot!
