### ISSUE TITLE
FPS

### ISSUE THREAD

**Issue by chenll12345** [TQTQliu/GeFu#2]
Thank you for the great work, which has benefited me a lot. I would like to know what the FPS of this work is like, and is it capable of real-time performance? I don’t seem to recall seeing this metric in the paper.

**Comment by TQTQliu** [comment]
Hi, thanks for your attention. Since this work was primarily aimed at improving view quality, especially in challenging areas, we didn't emphasize speed. But you can find the inference time in Figure 1, which is 0.14s at 512 × 640 resolution, i.e., 7.14 FPS. The time overhead for each module is reported in Table II of supplementary materials.
